# Generated by Django 2.2.15 on 2020-08-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='Страница ShowRoom', help_text='название элемента, до 100 символов', max_length=100, verbose_name='Название элемента')),
                ('title_showroom_page', models.CharField(default='Title страницы', help_text='до 200 символов', max_length=200, verbose_name='Title страницы')),
                ('description_showroom_page', models.CharField(default='Description страницы', help_text='до 450 символов', max_length=450, verbose_name='Description страницы')),
                ('name', models.CharField(help_text='длина до 200 символов', max_length=200, verbose_name='Заголовок на странице')),
                ('slug', models.SlugField(blank=True, help_text='URL-адрес до 200 символов', max_length=200, verbose_name='(Ссылка)')),
                ('content', models.TextField(help_text='длина до 3000 символов', verbose_name='Содержимое')),
            ],
            options={
                'verbose_name_plural': 'Страница ShowRoom: настройки',
                'verbose_name': 'Страница ShowRoom: настройки',
            },
        ),
        migrations.CreateModel(
            name='FotogaleryShowRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altimg', models.CharField(blank=True, help_text='Атрибут ALT для изображения, необязательно', max_length=150, verbose_name='ALT')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='showroom_images/', verbose_name='Загрузить фото')),
                ('showroomimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='showroom.ShowRoomModel')),
            ],
            options={
                'verbose_name_plural': 'Изображения на странице',
                'verbose_name': 'Фотогалерея',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentstype', to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotocontent', to='showroom.FotogaleryShowRoom')),
            ],
        ),
    ]
