# Generated by Django 2.2.15 on 2020-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='длина до 200 символов', max_length=200, verbose_name='Заголовок статьи')),
                ('titleseo', models.CharField(blank=True, help_text='длина до 200 символов', max_length=200, null=True, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, null=True, verbose_name='SEO Description')),
                ('slug', models.SlugField(blank=True, help_text='URL-адрес до 200 символов', max_length=200, verbose_name='(Ссылка)')),
                ('content', models.TextField(help_text='длина до 3000 символов', max_length=3000, verbose_name='Содержимое')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='PageNewsSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Страница - Новости', help_text='Модель для хранения SEO на странице Новости', max_length=100, verbose_name='Название страницы')),
                ('title', models.CharField(blank=True, default='Новости на сайте интернет-магазина Маргроид', help_text='Длина Title до 200 символов', max_length=200, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, default='Новости на сайте интернет-магазина Маргроид', help_text='Длина Description до 450 символов', max_length=450, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
    ]
