# Generated by Django 2.2.15 on 2020-08-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='длина до 100 символов', max_length=100, verbose_name='Название категории')),
                ('title', models.CharField(blank=True, help_text='длина до 200 символов', max_length=200, null=True, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(null=True, upload_to='category_images', verbose_name='Изображение категории')),
                ('slug', models.SlugField(help_text='длина на латинице до 100 символов', max_length=100, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='длина до 100 символов', max_length=100, verbose_name='Название подкатегории')),
                ('title', models.CharField(blank=True, help_text='длина до 200 символов', max_length=200, null=True, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, null=True, verbose_name='SEO Description')),
                ('image', models.ImageField(null=True, upload_to='category_images', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='длина до 100 символов', max_length=100, verbose_name='URL-адрес')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('image', models.ImageField(null=True, upload_to='product_colors', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(default=3000, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('title', models.CharField(blank=True, help_text='длина до 200 символов', max_length=200, null=True, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, help_text='длина до 450 символов', max_length=450, null=True, verbose_name='SEO Description')),
                ('slug', models.SlugField(blank=True, help_text='URL-адрес до 200 символов', max_length=200, verbose_name='(Ссылка)')),
                ('image', models.ImageField(null=True, upload_to='product_images', verbose_name='Изображение')),
                ('textproduct', models.TextField(blank=True, help_text='описание товара необязательно', null=True, verbose_name='Описание товара')),
                ('vendor_code', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='Наличие (шт)')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена')),
                ('on_sale', models.BooleanField(blank=True, default=False, verbose_name='На скидке')),
                ('sale', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Размер скидки')),
                ('new_price', models.PositiveIntegerField(blank=True, help_text='Вычисляется само при сохранении', null=True, verbose_name='Новая цена')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Категория')),
                ('color', models.ManyToManyField(blank=True, to='product.Colors', verbose_name='Цвета')),
                ('complect', models.ManyToManyField(blank=True, to='product.Product', verbose_name='Комплектующие')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.CategoryChild', verbose_name='Подкатегория')),
            ],
            options={
                'ordering': ['-category', 'name', 'price'],
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('saleprice', models.PositiveIntegerField(blank=True, help_text='Вычисляется само при сохранении', null=True, verbose_name='Цена размера по скидке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Fotogalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altimg', models.CharField(blank=True, help_text='Атрибут ALT для изображения, необязательно', max_length=150, verbose_name='ALT')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='product_images/', verbose_name='Загрузить фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='product.Product')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Изображения товара',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='product.Fotogalery')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subtype',
            field=models.ManyToManyField(blank=True, to='product.CategoryChild', verbose_name='Подкатегории'),
        ),
    ]
