# Generated by Django 2.2.15 on 2020-08-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorsSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('saleprice', models.PositiveIntegerField(blank=True, help_text='Вычисляется само при сохранении', null=True, verbose_name='Цена по скидке')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Colors', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sizes', verbose_name='Продукт (с размером)')),
            ],
            options={
                'verbose_name_plural': 'Цены цветов',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.ShopUser')),
            ],
            options={
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
