# Generated by Django 2.2.15 on 2020-09-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_productcolorssizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '01: Категория', 'verbose_name_plural': '01: Категории'},
        ),
        migrations.AlterModelOptions(
            name='categorychild',
            options={'verbose_name': '02: Подкатегория', 'verbose_name_plural': '02: Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': '05: Цвет товара', 'verbose_name_plural': '05: Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-category', 'name', 'price'], 'verbose_name': '03: Товар', 'verbose_name_plural': '03: Товары'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': '04: Размер товара', 'verbose_name_plural': '04: Размеры'},
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='colors_product', to='product.Colors', verbose_name='Цвета'),
        ),
    ]
