# Generated by Django 2.2.15 on 2020-08-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='Шапка сайта', help_text='название элемента, до 100 символов', max_length=100, verbose_name='Название элемента')),
                ('header_logo', models.ImageField(help_text='изображение может обрезаться', upload_to='logo/', verbose_name='Логотип сайта')),
                ('alt_logo_header', models.CharField(blank=True, help_text='Атрибут ALT для SEO, до 100 символов', max_length=100, verbose_name='Атрибут ALT для логотипа')),
                ('phone_one', models.CharField(blank=True, help_text='пишется ф формате: +7(999)-888-6655', max_length=20, verbose_name='Номер телефона 1')),
                ('phone_two', models.CharField(blank=True, help_text='пишется ф формате: +7(999)-888-6655', max_length=20, verbose_name='Номер телефона 2')),
            ],
            options={
                'verbose_name': 'Шапка сайта: настройки',
                'verbose_name_plural': 'Шапка сайта: настройки',
            },
        ),
        migrations.CreateModel(
            name='SeoHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='Мета-теги главной страницы', help_text='название элемента, до 100 символов', max_length=100, verbose_name='Название элемента')),
                ('title_home_page', models.CharField(default='Title главной страницы', help_text='до 200 символов', max_length=200, verbose_name='Title длавной страницы')),
                ('description_home_page', models.CharField(default='Description главной страницы', help_text='до 450 символов', max_length=450, verbose_name='Description длавной страницы')),
            ],
            options={
                'verbose_name': 'Главная страница: SEO',
                'verbose_name_plural': 'Главная страница: SEO',
            },
        ),
    ]
