# Generated by Django 2.2.15 on 2020-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seohomepage',
            name='description_home_page',
            field=models.CharField(default='Description главной страницы', help_text='до 450 символов', max_length=450, verbose_name='Description главной страницы'),
        ),
        migrations.AlterField(
            model_name='seohomepage',
            name='title_home_page',
            field=models.CharField(default='Title главной страницы', help_text='до 200 символов', max_length=200, verbose_name='Title главной страницы'),
        ),
    ]
