# Generated by Django 2.2.15 on 2020-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200829_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlockHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='Контакты', help_text='название элемента, до 100 символов', max_length=100, verbose_name='Название элемента')),
                ('text_header', models.CharField(blank=True, help_text='Текст до 200 символов', max_length=200, verbose_name='Текст или адрес')),
                ('phone_one', models.CharField(blank=True, help_text='пишется ф формате: +7(999)-888-6655', max_length=20, verbose_name='Номер телефона 1')),
            ],
            options={
                'verbose_name_plural': 'Блок контакты на главной: настройки',
                'verbose_name': 'Блок контакты на главной: настройки',
            },
        ),
    ]
