# Generated by Django 2.2.15 on 2020-08-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactblockhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBlockFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='Контакты', help_text='название элемента, до 100 символов', max_length=100, verbose_name='Название элемента')),
                ('text_header', models.CharField(blank=True, help_text='Текст до 200 символов', max_length=200, verbose_name='Текст или адрес')),
                ('email', models.EmailField(default='Margroid@mai.ru', max_length=254, verbose_name='Электронная почта')),
                ('phone_one', models.CharField(blank=True, help_text='пишется ф формате: +7(999)-888-6655', max_length=20, verbose_name='Номер телефона 1')),
                ('phone_two', models.CharField(blank=True, help_text='пишется ф формате: +7(999)-888-6655', max_length=20, verbose_name='Номер телефона 2')),
            ],
            options={
                'verbose_name_plural': '03: Блок контакты на главной: настройки',
                'verbose_name': '03: Блок контакты на главной: настройки',
            },
        ),
        migrations.AlterModelOptions(
            name='contactblockhomepage',
            options={'verbose_name': '03: Блок контакты на главной: настройки', 'verbose_name_plural': '03: Блок контакты на главной: настройки'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': '02: Шапка сайта: настройки', 'verbose_name_plural': '02: Шапка сайта: настройки'},
        ),
        migrations.AlterModelOptions(
            name='seohomepage',
            options={'verbose_name': '01: Главная страница: SEO', 'verbose_name_plural': '01: Главная страница: SEO'},
        ),
    ]
