# Generated by Django 2.2.15 on 2020-08-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
        ('product', '0002_comment_productcolorssizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_images', verbose_name='Изображение')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Информация о доставке',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Почта')),
                ('delivery_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ доставки')),
                ('delivery_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('delivery_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('delivery_house', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('delivery_padik', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда')),
                ('delivery_flat', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('delivery_deadline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сроки')),
                ('take_away_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес при самовывозе')),
                ('transport_company_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес транспортной компании')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип оплаты')),
                ('org_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование организации')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('legal_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юридический адрес')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('Выполнен', 'Выполнен'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен'), ('Выдан', 'Выдан')], default='Оформлен', max_length=20)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authuser.ShopUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PageCartSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Страница - Корзина', help_text='Модель для хранения SEO на странице Корзина', max_length=100, verbose_name='Название страницы')),
                ('title', models.CharField(blank=True, default='Корзина', help_text='Длина Title до 200 символов', max_length=200, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, default='Корзина', help_text='Длина Description до 450 символов', max_length=450, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name_plural': 'Корзина',
                'verbose_name': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='StandartSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.PositiveSmallIntegerField(default=0, verbose_name='Стандартная скидка')),
            ],
            options={
                'verbose_name_plural': 'Стандартная скидка',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Sizes')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_item_color', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Sizes')),
            ],
            options={
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, to='cart.CartItem')),
            ],
            options={
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
