# Generated by Django 2.2.15 on 2020-08-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPageSeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Доставка в интернет-магазине Маргроид', help_text='Модель для хранения SEO на странице Доставка', max_length=100, verbose_name='Название страницы')),
                ('title', models.CharField(blank=True, default='Доставка в интернет-магазине Маргроид', help_text='Длина Title до 200 символов', max_length=200, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, default='Доставка в интернет-магазине Маргроид', help_text='Длина Description до 450 символов', max_length=450, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name_plural': 'SEO для страницы Доставка',
                'verbose_name': 'SEO для страница Доставка',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина: товары в корзине', 'verbose_name_plural': 'Корзины: товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'Информация о доставке', 'verbose_name_plural': 'Информация о доставке'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Продукт в заказе', 'verbose_name_plural': 'Продукт в заказе'},
        ),
        migrations.AlterModelOptions(
            name='pagecartseo',
            options={'verbose_name': 'SEO для Корзины', 'verbose_name_plural': 'SEO для Корзины'},
        ),
        migrations.AlterModelOptions(
            name='standartsale',
            options={'verbose_name': 'Стандартная скидка', 'verbose_name_plural': 'Стандартная скидка'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='cart.CartItem', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма'),
        ),
    ]
