# Generated by Django 2.2.15 on 2020-08-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0002_auto_20200829_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypageseo',
            options={'verbose_name': '01: Настройки - Доставка', 'verbose_name_plural': '01: Настройки страницы Доставка'},
        ),
        migrations.AddField(
            model_name='deliverypageseo',
            name='content',
            field=models.TextField(default=0, help_text='длина до 3000 символов', max_length=3000, verbose_name='Содержимое'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverypageseo',
            name='name',
            field=models.CharField(default='Доставка', help_text='Модель для хранения SEO на странице Доставка', max_length=100, verbose_name='Название страницы'),
        ),
        migrations.CreateModel(
            name='FotogaleryShowRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_img', models.CharField(blank=True, help_text='Описание преимущества до 150 символов', max_length=150, verbose_name='Описание преимущества до 150 символов')),
                ('altimg', models.CharField(blank=True, help_text='Атрибут ALT для изображения, необязательно', max_length=150, verbose_name='ALT')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='delivery_images/', verbose_name='Загрузить фото')),
                ('showroomimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotosdelivery', to='cart.DeliveryPageSeo')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Изображения на странице',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentstypedelivery', to='contenttypes.ContentType')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotocontentdelivery', to='cart.FotogaleryShowRoom')),
            ],
        ),
    ]
