# Generated by Django 2.2.15 on 2020-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200829_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypageseo',
            name='content',
            field=models.TextField(blank=True, help_text='длина до 3000 символов', max_length=3000, verbose_name='Содержимое'),
        ),
    ]
