# Generated by Django 2.2.15 on 2020-09-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200829_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '03: Корзина: товары в корзине', 'verbose_name_plural': '03: Корзины: товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '05: Заказ', 'verbose_name_plural': '05: Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pagecartseo',
            options={'verbose_name': '02: SEO для Корзины', 'verbose_name_plural': '02: SEO для Корзины'},
        ),
        migrations.AlterModelOptions(
            name='standartsale',
            options={'verbose_name': '04: Стандартная скидка', 'verbose_name_plural': '04: Стандартная скидка'},
        ),
    ]
